# elpis-linux -- builds the Elpis appliance ISO with Buildroot.
#
#   make                  fetch Buildroot the first time, configure, build
#   make RESOLVER_SRC=../elpis-resolver
#                         build the resolver from a local checkout instead of
#                         the release tag
#   make ELPIS_LINUX_VERSION=0.1.1-test
#                         a version other than the one in ./VERSION
#   make menuconfig       anything else is passed through to Buildroot:
#   make linux-menuconfig   menuconfig, savedefconfig, elpis-resolver-rebuild,
#   make legal-info         legal-info, ...
#   make clean            remove output/ (downloads in dl/ are kept)
#
# The result is output/images/elpis-<version>-x86_64.iso.

BR_VERSION := 2026.02.3
BR_SHA256  := 5a59e7501b0b4ec52c41f4bfa79412320e0b37eae5f719605a258e8d0c6fc7fb
BR_TARBALL := buildroot-$(BR_VERSION).tar.xz
BR_URL     := https://buildroot.org/downloads/$(BR_TARBALL)
BR_DIR     := $(CURDIR)/.buildroot/buildroot-$(BR_VERSION)

O         ?= $(CURDIR)/output
DEFCONFIG ?= elpis_x86_64_defconfig

# Source tarballs are kept across `make clean`.
export BR2_DL_DIR ?= $(CURDIR)/dl

# Update signing, both optional (see README.md):
#   UPDATE_PUBKEY  minisign public key built into the image; elpis-update
#                  then refuses an update that this key did not sign
#   SIGNING_KEY    minisign secret key that signs the finished ISO
UPDATE_PUBKEY ?= $(wildcard $(CURDIR)/keys/update.pub)
SIGNING_KEY   ?=
export ELPIS_UPDATE_PUBKEY := $(if $(UPDATE_PUBKEY),$(abspath $(UPDATE_PUBKEY)))
export ELPIS_SIGNING_KEY   := $(if $(SIGNING_KEY),$(abspath $(SIGNING_KEY)))

RESOLVER_SRC ?=

# The appliance's version, normally from ./VERSION.  Not called VERSION:
# command-line variables reach every sub-make, and the kernel has its own.
ELPIS_LINUX_VERSION ?= $(shell cat $(CURDIR)/VERSION)
export ELPIS_LINUX_VERSION

BR_MAKE = $(MAKE) -C $(BR_DIR) O=$(O) BR2_EXTERNAL=$(CURDIR)

.PHONY: all iso config clean distclean FORCE
all: iso

iso: $(O)/.config $(O)/local.mk
	$(BR_MAKE)

# Re-read configs/$(DEFCONFIG), dropping changes made with menuconfig.
config: | $(BR_DIR)
	$(BR_MAKE) $(DEFCONFIG)

$(O)/.config: | $(BR_DIR)
	$(BR_MAKE) $(DEFCONFIG)

# Buildroot takes package overrides from $(O)/local.mk.  It is rewritten when
# RESOLVER_SRC changes; after switching, `make elpis-resolver-dirclean` so the
# resolver is fetched or copied again.
$(O)/local.mk: FORCE
	@mkdir -p $(O)
	@printf '%s\n' '# generated by elpis-linux/Makefile from RESOLVER_SRC' \
	    $(if $(RESOLVER_SRC),'ELPIS_RESOLVER_OVERRIDE_SRCDIR = $(abspath $(RESOLVER_SRC))') \
	    > $@.tmp
	@if cmp -s $@.tmp $@; then rm -f $@.tmp; else mv -f $@.tmp $@; fi

$(BR_DIR):
	mkdir -p $(dir $@)
	cd $(dir $@) && \
	    { [ -f $(BR_TARBALL) ] || curl -fL -o $(BR_TARBALL) $(BR_URL); } && \
	    echo "$(BR_SHA256)  $(BR_TARBALL)" | sha256sum -c - && \
	    tar xf $(BR_TARBALL)

clean:
	rm -rf $(O)

distclean: clean
	rm -rf .buildroot dl

Makefile: ;

# Everything else is a Buildroot target.
%: $(O)/.config FORCE
	$(BR_MAKE) $@
